# Pandas-DataFrame And Series

Pandas is a powerful data manipulation library in Python, wisely used for data analysis and data cleaning.It provides two primary data structures:Series and DataFrame. A series is a one-dimensional array-like object,while a Dataframe is a two-dimensional , size-mutable , and potentially heterogeneous tabular data structure with labeled axes (rows and coloumns).

In [6]:
import pandas as pd

In [7]:
## Series
## A Pandas Series is a one-deimensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data =[1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
## Create a series fro, Dictionary 
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [9]:
data =[10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [10]:
## DataFrame
## create a Dataframe from a Dictionary of list

data = {
  'Name':['Taleeb','Kaifudaa','azizudaa','danisya'],
  'Age':[21,99,5,20],
  'City':['Dubai','Natikybaada','Jopda','Dubai']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age         City
0    Taleeb   21        Dubai
1  Kaifudaa   99  Natikybaada
2  azizudaa    5        Jopda
3   danisya   20        Dubai
<class 'pandas.core.frame.DataFrame'>

In [11]:
import numpy as np
np.array(df)

array([['Taleeb', 21, 'Dubai'],
       ['Kaifudaa', 99, 'Natikybaada'],
       ['azizudaa', 5, 'Jopda'],
       ['danisya', 20, 'Dubai']], dtype=object)

In [12]:
## Create a DataFrame from a list of Dictionaries

data = [
  {'Name':'Taleeb','Age':30,'City':'Saudi'},
  {'Name':'Danish','Age':29,'City':'Dubai'},
  {'Name':'kaif','Age':32,'City':'Newyork'},
  {'Name':'Aziz','Age':31,'City':'Canada'}

]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada
<class 'pandas.core.frame.DataFrame'>

In [11]:
df = pd.read_csv('customers-1000.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [12]:
df.tail(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [13]:
## Accessing Data From DataFrame
df

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df['Name'] # Accessing a single column as a Series

0      Taleeb
1    Kaifudaa
2    azizudaa
3     danisya
Name: Name, dtype: object

In [ ]:
df.loc[0] # Access the first row of the DataFrame using loc

Name    Taleeb
Age         21
City     Dubai
Name: 0, dtype: object

In [ ]:
df.iloc[0] # Access the first row of the DataFrame using iloc (integer location)

Name    Taleeb
Age         21
City     Dubai
Name: 0, dtype: object

In [ ]:
df.loc[0][0] # Access the first element of the first row using loc

C:\Users\HP\AppData\Local\Temp\ipykernel_16708\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Taleeb'

In [25]:
df.iloc[0][2] # Access the second element of the first row using iloc

C:\Users\HP\AppData\Local\Temp\ipykernel_16708\3954433895.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2] # Access the second element of the first row using iloc

'Dubai'

In [14]:
## Accessing a specified element
df

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [ ]:
df.at[1,'Age'] # Access the element at row index 1 and column 'Age' using at

np.int64(99)

In [29]:
df.at[2,'Name'] # Access the element at row index 2 and column 'Name' using at

'azizudaa'

In [15]:
## Accessing a specified element using iat 
df.iat[2,2]

'Newyork'

In [16]:
df

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [17]:
## Data Manipulation with DataFrame
df

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [ ]:
# Adding a new column to the DataFrame
df['salary'] = [450000,470000,430000,500000] 
df

     Name  Age     City  salary
0  Taleeb   30    Saudi  450000
1  Danish   29    Dubai  470000
2    kaif   32  Newyork  430000
3    Aziz   31   Canada  500000

In [19]:
# removing a column from the DataFrame
df.drop('salary',axis=1)

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [ ]:
df # The original DataFrame remains unchanged after dropping the column, unless we specify inplace=True.

     Name  Age     City  salary
0  Taleeb   30    Saudi  450000
1  Danish   29    Dubai  470000
2    kaif   32  Newyork  430000
3    Aziz   31   Canada  500000

In [21]:
df.drop('salary',axis=1,inplace=True) # This will permanently remove the 'salary' column from the DataFrame
df

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [ ]:
df

     Name  Age     City
0  Taleeb   30    Saudi
1  Danish   29    Dubai
2    kaif   32  Newyork
3    Aziz   31   Canada

In [23]:
## Add age to the column age
df['Age'] = df['Age']+1
df

     Name  Age     City
0  Taleeb   31    Saudi
1  Danish   30    Dubai
2    kaif   33  Newyork
3    Aziz   32   Canada

In [25]:
df.drop(0,inplace=True) # This will permanently remove the row with index 0 from the DataFrame
df

     Name  Age     City
1  Danish   30    Dubai
2    kaif   33  Newyork
3    Aziz   32   Canada

In [26]:
df = pd.read_csv('customers-1000.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/

In [ ]:
# Display the data types of each column in the DataFrame
print("Data types : \n",df.dtypes)

#Describe the dataframe
print("statistical summary : \n",df.describe())

Data types :
 Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object
statistical summary :
              Index
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [28]:
df.describe() # This will provide a statistical summary of the DataFrame.

             Index
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000